steps:
  - name: docker
    args:
      - build
      - "-t"
      - "$LOCATION-docker.pkg.dev/$PROJECT_ID/wcf/wcf-ui:$SHORT_SHA"
      - .
  # - name: "gcr.io/cloud-builders/gke-deploy"
  #   args:
  #     - run
  #     - --namespace=default
  #     - --app=wcf-ui
  #     - --location=asia-northeast2
  #     - --cluster=wcf
  #     - --image=$LOCATION-docker.pkg.dev/$PROJECT_ID/wcf/wcf-ui:$SHORT_SHA
images:
  - "$LOCATION-docker.pkg.dev/$PROJECT_ID/wcf/wcf-ui:$SHORT_SHA"
options:
  logging: CLOUD_LOGGING_ONLY
