steps:
  - name: docker
    args:
      - build
      - "-t"
      - "$LOCATION-docker.pkg.dev/$PROJECT_ID/wcf/wcf-ui:$TAG_NAME"
      - .
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --namespace=default
      - --app=wcf-ui
      - --location=asia-northeast2
      - --cluster=wcf
      - --image=$LOCATION-docker.pkg.dev/$PROJECT_ID/wcf/wcf-ui:$TAG_NAME
images:
  - "$LOCATION-docker.pkg.dev/$PROJECT_ID/wcf/wcf-ui:$TAG_NAME"
options:
  logging: CLOUD_LOGGING_ONLY
